### ISSUE TITLE
[WinError 2] The system cannot find the file specified 

### ISSUE THREAD

**Issue by 45656456kawai** [Tesla-Nikola-2012/NordVPN_Randomizer#1]
help! I'm getting that error

**Comment by jm20122012** [comment]
Do you have NordVPN installed?  What distro are you running?

**Comment by hulla-bulla** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'nordvpn': 'nordvpn' on MacOSX, got both NordVPN Ike and NordVPN installed, tried with both. 

Hos is the script communicating with nordvpn? Can I test something on the terminal? Got some links or anything that I can try debug through? The script looks nice though!

**Comment by jm20122012** [comment]
This script was written and tested on Ubuntu Linux.  I'm not 100% sure how you could edit this to make it work on Mac as I never use Mac, and unfortunately I don't have any plans to in the near future.

The script basically makes use of the subprocess command in python to get the status of the NordVPN client as if you were in the terminal (bash).  I know that as far as the terminal goes, Mac and Linux are supposed to be almost identical, but I don't know enough about Mac to troubleshoot why this might not be working for you.  Sorry about that, but unfortunately I can't help as this was written for Linux, not Mac.

**Comment by jm20122012** [comment]
Closing since issue is Mac related and this program was written for Linux.
